const config = require('../../Coinfigs/config.json')

module.exports = {
    commands: 'admin',
    expectedArgs: '',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, args, text, Discord, client, admin) => {
        const commandsEN = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('Commands')
                .addFields(
                    {name: '-Admin', value: 'to list all the ADMINISTRATOR commands'},
                    {name: '-Command', value: 'to disable or enable any command'},
                    {name: '-Anncounce', value: 'to announce something in the announcement chat'},
                    {name: '-Prems', value: 'to delete or add perms to any command'},
                    {name: '-Rules', value: 'to set the rules in the rules chat'},
                    {name: '-Status', value: 'to turn off or on the bot'},
                )
                .setDescription('Here is all the current commands enjoy (=')
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(commandsEN);
    },
    requiredRoles: []
}