const error = require('../Errors')
const FortniteAPI = require("fortnite-api-com");
const key = require('../../Coinfigs/config.json')
const config = {
  apikey: key.apis.fortniteapi,
  language: "en",
  debug: true
};

var Fortnite = new FortniteAPI(config);

module.exports = {
    commands: 'aes',
    expectedArgs: '',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, args, text, Discord, client, admin, alias, errorEmoji, checkEmoji) => {
        admin.database().ref("ERA's").child("Users").child(message.author.id).once('value', function (data) {
            var lang = data.val().lang;

            Fortnite.AES("en")
                .then( async res => {
                    if(lang == "en"){
                        const generating = new Discord.MessageEmbed()
                        generating.setColor('#BB00EE')
                        const emoji = client.emojis.cache.get("805690920157970442")
                        generating.setTitle(`Generating ... ${emoji}`)
                        message.channel.send(generating)
                            .then( async msg => {
                                const AES = new Discord.MessageEmbed()
                                .setColor('#BB00EE')
                                .setTitle('Update AES')
                                .setDescription('Getting the current AES!')
                                .addFields(
                                    {name: 'Build:', value: res.data.build},
                                    {name: 'AES Key:', value: res.data.mainKey},
                                )
                                .setFooter('Generated By FNBRMENA Bot')
                                .setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')
                                await message.reply(AES);
                                msg.delete()
                            }).catch(err => {
                                console.log(err);
                        });
                    }
                    if(lang == "ar"){
                        const generating = new Discord.MessageEmbed()
                        generating.setColor('#BB00EE')
                        const emoji = client.emojis.cache.get("805690920157970442")
                        generating.setTitle(`يتم التحميل ... ${emoji}`)
                        message.channel.send(generating)
                            .then( async msg => {
                                const AES = new Discord.MessageEmbed()
                                .setColor('#BB00EE')
                                .setTitle('Update AES')
                                .setDescription('مفتاح الـ AES الخاص بالتحديث الحالي')
                                .addFields(
                                    {name: 'التحديث:', value: res.data.build},
                                    {name: 'مفتاح الـ AES:', value: res.data.mainKey},
                                )
                                .setFooter('Generated By FNBRMENA Bot')
                                .setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')
                                await message.reply(AES);
                                msg.delete()
                            }).catch(err => {
                                console.log(err);
                        });
                    }
            }).catch(err => {
                error(err, message, args, text, Discord, client, admin, alias, errorEmoji, checkEmoji)
            })
        });
        
    },
    
    requiredRoles: []
}