const Data = require('../../FNBRMENA')
const FNBRMENA = new Data()
const FortniteAPI = require("fortnite-api-com");
const config = {
  apikey: FNBRMENA.APIKeys("FortniteAPI.com"),
  language: "en",
  debug: true
};

var Fortnite = new FortniteAPI(config);

module.exports = {
    commands: 'aes',
    minArgs: 0,
    maxArgs: 0,
    cooldown: -1,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: async (message, args, text, Discord, client, admin, alias, errorEmoji, checkEmoji, loadingEmoji) => {
        
        //get the user language from the database
        const lang = await FNBRMENA.Admin(admin, message, "", "Lang")

        //request dat
        Fortnite.AES("en")
        .then( async res => {

            //inisilizing data
            var paks = ""
            var counter = 1

            //send generating msg
            const generating = new Discord.MessageEmbed()
            generating.setColor(FNBRMENA.Colors("embed"))
            if(lang === "en") generating.setTitle(`Generating ... ${loadingEmoji}`)
            else if(lang === "ar") generating.setTitle(`جاري التحميل ... ${loadingEmoji}`)
            message.channel.send(generating)
            .then( async msg => {

                //loop throw every pak file
                for(let i = 0; i < res.data.dynamicKeys.length; i++){

                    //remove .ucan
                    if(!res.data.dynamicKeys[i].pakFilename.includes(".ucas") && !res.data.dynamicKeys[i].pakFilename.includes("optional")){

                        if(lang === "en"){

                            paks += "• Pak "+ counter +": " + res.data.dynamicKeys[i].pakFilename + "\n"
                            counter++
                        }else if(lang === "ar"){
            
                            paks += "• باك "+ counter +": " + res.data.dynamicKeys[i].pakFilename + "\n"
                            counter++
                        }
                    }
                }

                //create aes embed
                const AES = new Discord.MessageEmbed()

                //set the color
                AES.setColor(FNBRMENA.Colors("embed"))

                //set title
                if(lang === "en") AES.setTitle('AES key and paks')
                else if(lang === "ar") AES.setTitle('مفتاح الـ AES')
                
                //add fields
                if(lang === "en"){
                    AES.addFields(
                        {name: 'Build:', value: res.data.build},
                        {name: 'AES Key:', value: res.data.mainKey},
                        {name: 'Paks:', value: paks},
                    )
                }else if(lang === "ar"){
                    AES.addFields(
                        {name: 'التحديث:', value: res.data.build},
                        {name: 'مفتاح الـ AES:', value: res.data.mainKey},
                        {name: 'باك:', value: paks},
                    )
                }
                AES.setFooter('Generated By FNBRMENA Bot')
                AES.setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')
                await message.channel.send(AES);
                msg.delete()


            }).catch(err => {
                console.log(err);
            })

        }).catch(err => {
        
        })
    }
}