module.exports = {
    commands: 'help',
    type: 'Fortnite',
    minArgs: 0,
    maxArgs: 0,
    cooldown: -1,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: async (FNBRMENA, message, args, text, Discord, client, admin, userData, alias, emojisObject) => {
        const help = new Discord.EmbedBuilder()
        .setColor(FNBRMENA.Colors("embed"))
        .setTitle('Help Section')
        .addFields(
            {name: '-Commands', value: 'Use that command to find all the FNBRMENA bot commands'}
        )
        .setDescription('Go to help if you have any issues there you will find all the helpful content')
        .setFooter({text: 'Generated By FNBRMENA Bot'})
        .setAuthor({name: 'FNBRMENA Bot', iconURL: 'https://i.imgur.com/LfotEkZ.jpg', url: 'https://twitter.com/FNBRMENA'})
        message.reply({embeds: [help]});
    },
}