module.exports = {
    commands: 'help',
    expectedArgs: '<help>',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord) => {
        const help = new Discord.MessageEmbed()
        .setColor('#BB00EE')
        .setTitle('Help Section')
        .addFields(
            {name: '-Commands', value: 'Use that command to find all the FNBR_MENA bot commands'}
        )
        .setDescription('Go to help if you have any issues there you will find all the helpful content')
        .setFooter('Generated By FNBRMENA Bot')
        .setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')
        message.reply(help);
    },
    
    requiredRoles: []
}