const FortniteAPI = require("fortnite-api-com");
const config = {
  apikey: "a7eabb1fa5a6e59cbcda3a6885d42f02be0d76ea",
  language: "en",
  debug: true
};

var Fortnite = new FortniteAPI(config);

module.exports = {
    commands: 'news',
    expectedArgs: '<BR> <STW> <Creative>',
    minArgs: 1,
    maxArgs: 1,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord, client, server) => {

        if(arguments[0] === 'br'){
            Fortnite.NewsBR("ar")
            .then(res => {
                console.log(res.data);
                for (let i = 0; i < res.data.motds.length; i++){
                const News = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('BR Live News')
                .setImage(res.data.motds[i].image)
                .setDescription('This is the current In-Game news')
                .addFields(
                    {name: 'Title', value: res.data.motds[i].title},
                    {name: 'Description', value: res.data.motds[i].body}
                )
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(News);
                }
            }).catch(err => {
                console.log(err);
        });
        }else if(arguments[0] === 'stw'){
            Fortnite.NewsSTW("ar")
            .then(res => {
                console.log(res.data);
                for (let i = 0; i < res.data.messages.length; i++){
                const News = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('STW Live News')
                .setImage(res.data.messages[i].image)
                .setDescription('This is the current In-Game news')
                .addFields(
                    {name: 'Title', value: res.data.messages[i].title},
                    {name: 'Description', value: res.data.messages[i].body}
                )
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(News);
                }
            }).catch(err => {
                console.log(err);
        });
        }else if(arguments[0] === 'creative'){
            Fortnite.NewsCreative("ar")
            .then(res => {
                console.log(res.data);
                for (let i = 0; i < res.data.motds.length; i++){
                const News = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('Creative Live News')
                .setImage(res.data.motds[i].image)
                .setDescription('This is the current In-Game news')
                .addFields(
                    {name: 'Title', value: res.data.motds[i].title},
                    {name: 'Description', value: res.data.motds[i].body}
                )
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(News);
                }
            }).catch(err => {
                console.log(err);
        });
        }
    },
    
    requiredRoles: []
}