const axios = require('axios');

module.exports = {
    commands: 'notice',
    expectedArgs: '<Notice>',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord) => {
        axios.get('https://fn-api.com/api/emergencynotice')
        .then((res) => {
            console.log(res.data.messages)
            if (res.data.messages.length !== 0){
            if (res.data.messages[0].title === 'Scheduled Downtime'){
                const Notice = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('Active Notices')
                .setImage('https://i.imgur.com/coYBRPs.jpg')
                .setDescription('Here you can see what is broken in Fortnite')
                .addFields(
                    {name: 'Title', value: res.data.messages[0].title},
                    {name: 'Description', value: res.data.messages[0].body}
                )
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(Notice);
            }else{
                const Notice = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('Active Notices')
                .setImage('https://i.imgur.com/nYo2dxe.jpg')
                .setDescription('Here you can see what is broken in Fortnite')
                .addFields(
                    {name: 'Title', value: res.data.messages[0].title},
                    {name: 'Description', value: res.data.messages[0].body}
                )
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://cdn.discordapp.com/attachments/756516105677177034/801215605461876776/THxzewFr_400x400.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(Notice);
            }
         }else{
             const Notice = new Discord.MessageEmbed()
                 .setColor('#BB00EE')
                 .setTitle('Active Notices')
                 .setImage('https://i.imgur.com/k4Bhvfc.jpg')
                 .setDescription('Here you can see what is broken in Fortnite')
                 .addFields(
                     {name: 'Title', value: 'Hmmmm'},
                     {name: 'Description', value:'Nothing is disabled ay the moment'}
                 )
                 .setFooter('Generated By FNBR_MENA Bot')
                 .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                 message.reply(Notice);
         }
        })
        .catch((err) => {
            console.log(err)
        })
    },
    
    requiredRoles: []
}