const axios = require('axios');

module.exports = {
    commands: 'playlists',
    expectedArgs: '<Playlists>',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord) => {
        axios.get('https://fn-api.com/api/activeplaylists')
        .then((res) => {
            console.log(res.data);
            for (let i = 0; i < res.data.activePlaylists.length; i++){
                const exampleEmbed = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('Active Playlist')
                .setImage(res.data.activePlaylists[i].image)
                .addFields(
                    {name: 'Mode Name', value: res.data.activePlaylists[i].id}
                )
                .setDescription('The mode ' + res.data.activePlaylists[i].id + ' is an active playlist at the moment')
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(exampleEmbed);
            }
        })
        .catch((err) => {
            console.log(err)
        })
    },
    
    requiredRoles: []
}