const axios = require('axios');
const Canvas = require('canvas')

module.exports = {
    commands: 'progress',
    expectedArgs: '<Progress>',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord, client) => {
        axios.get('https://api.peely.de/v1/br/progress/data')
        .then(async (res) => {
            console.log(res.data);

            const generating = new Discord.MessageEmbed()
            generating.setColor('#BB00EE')
            const emoji = client.emojis.cache.get("805690920157970442")
            generating.setTitle(`Generating Season Info ... ${emoji}`)
            message.channel.send(generating)
            .then( async msg => {

            var percentage = (res.data.data.DaysGone / res.data.data.SeasonLength);
            var length = 1014 * percentage

            //canvas
            const canvas = Canvas.createCanvas(1100, 300);
            const ctx = canvas.getContext('2d'); 

            //background
            const background = await Canvas.loadImage('./assets/Bar/card.png')
            ctx.drawImage(background, 0, 0, canvas.width, canvas.height)
            ctx.fillStyle = '#ffffff';
            ctx.textAlign='center';
            ctx.font = 'normal 25px Burbank Big Condensed'
            ctx.fillText("Season Length "+ res.data.data.SeasonLength +" Days", (1100 / 2), 290)

            //bar
            const bar = await Canvas.loadImage('./assets/Bar/Bar.png')
            ctx.drawImage(bar, 50, 131, length, 34)
            ctx.fillStyle = '#ffffff';
            ctx.textAlign='center';
            ctx.font = 'normal 30px Burbank Big Condensed'
            ctx.fillText(((percentage * 100) | 0) + "%", (length + 20), 158)

            //gone
            const gone = await Canvas.loadImage('./assets/Bar/green.png')
            ctx.drawImage(gone, 50, 175, length, 11)
            ctx.fillStyle = '#ffffff';
            ctx.textAlign='center';
            ctx.font = 'normal 30px Burbank Big Condensed'
            ctx.fillText(res.data.data.DaysGone+" Days Gone", (length / 2), 215)

            //left
            var leftlength = ((res.data.data.DaysLeft + 1) / res.data.data.SeasonLength)
            var leftt = 1014 * leftlength
            const left = await Canvas.loadImage('./assets/Bar/BarWhite.png')
            ctx.drawImage(left, (length + 50), 115, leftt, 11)
            ctx.fillStyle = '#ffffff';
            ctx.textAlign='center';
            ctx.font = 'normal 30px Burbank Big Condensed'
            ctx.fillText(res.data.data.DaysLeft+" Days Left", (length + (leftt / 2) + 50), 105)

            //season
            ctx.fillStyle = '#ffffff';
            ctx.textAlign='left';
            ctx.font = 'normal 60px Burbank Big Condensed'
            ctx.fillText("Season 5 Chapter 2", 50, 70)

            const att = new Discord.MessageAttachment(canvas.toBuffer(), "season5.png")
            await message.channel.send(att)

            const progress = new Discord.MessageEmbed()
            progress.setColor('#BB00EE')
            progress.setTitle('Progress Bar')
            progress.setDescription('FNBR_MENA Bot has generated a season progress for you')
            progress.addFields(
                    {name: 'Days Left', value: res.data.data.DaysLeft, inline: true},
                    {name: 'Days Gone', value: res.data.data.DaysGone, inline: true},
                    {name: 'Season Length', value: res.data.data.SeasonLength, inline: true}
                )
                progress.setFooter('Generated By FNBR_MENA Bot')
                progress.setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(progress);
                msg.delete()
            })
            .catch((err) => {
                console.log(err)
            })
        })
        .catch((err) => {
            console.log(err)
        })
    },
    
    requiredRoles: []
}