const FortniteAPI = require("fortnite-api-com");
const config = {
  apikey: "a7eabb1fa5a6e59cbcda3a6885d42f02be0d76ea",
  language: "en",
  debug: true
};
var f;

var Fortnite = new FortniteAPI(config);

module.exports = {
    commands: 'sac',
    expectedArgs: '<sac>',
    minArgs: 1,
    maxArgs: 1,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord, client) => {

        Fortnite.CreatorCodeSearch(arguments)
            .then( async res => {
                console.log(res)

                const lang = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('Choose a language please')
                .addFields(
                    {name: 'Arabic', value: 'React to the Saudi Arabia flag :flag_sa:'},
                    {name: 'English', value: 'React to the US flag :flag_us:'}
                )
                const msgReact = await message.channel.send(lang)
                await msgReact.react('🇸🇦')
                msgReact.react('🇺🇸')
                const filter = (reaction, user) => {
                    return ['🇸🇦', '🇺🇸'].includes(reaction.emoji.name) && user.id === message.author.id;
                };
                msgReact.awaitReactions(filter, { max: 1, time: 60000, errors: ['time'] })
                            .then( async collected => {
                                const reaction = collected.first();

                                const generating = new Discord.MessageEmbed()
                                generating.setColor('#BB00EE')
                                const emoji = client.emojis.cache.get("805690920157970442")
                                generating.setTitle(`Getting SAC info ... ${emoji}`)
                                message.channel.send(generating)
                                .then( async msg => {

                                if(reaction.emoji.name === '🇺🇸'){
                                    msgReact.delete({timeout: 500})
                                    console.log(res.data);
                                    if (res.data.verified === false){
                                        f = 'Not yet'
                                    }else{
                                        f = 'Yes it is';
                                    }
                                        const sac = new Discord.MessageEmbed()
                                        .setColor('#BB00EE')
                                        .setTitle('SAC Information')
                                        .setDescription('Here is the information for ' + arguments + ' SAC')
                                        .addFields(
                                            {name: 'Code:', value: res.data.code},
                                            {name: 'Name:', value: res.data.account.name},
                                            {name: 'Status:', value: res.data.status},
                                            {name: 'Verified:', value: f}
                                        )
                                        .setFooter('Generated By FNBR_MENA Bot')
                                        .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                                        await message.reply(sac);
                                        msg.delete({timeout: 500})
                                }
                                if(reaction.emoji.name === '🇸🇦'){
                                    msgReact.delete({timeout: 500})
                                    console.log(res.data);
                                    if (res.data.verified === false){
                                        f = 'Not yet'
                                    }else{
                                        f = 'Yes it is';
                                    }
                                        const sac = new Discord.MessageEmbed()
                                        .setColor('#BB00EE')
                                        .setTitle('SAC Information')
                                        .setDescription('جميع المعلومات الخاصة بكود ' + arguments)
                                        .addFields(
                                            {name: 'الكود:', value: res.data.code},
                                            {name: 'الاسم:', value: res.data.account.name},
                                            {name: 'حالة الكود:', value: res.data.status},
                                            {name: 'توثيق الكود:', value: f}
                                        )
                                        .setFooter('Generated By FNBR_MENA Bot')
                                        .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                                        await message.reply(sac);
                                        msg.delete({timeout: 500})
                                }
                                    }).catch(err => {
                                        console.log(err);
                                });
                            }).catch(err => {
                                msgReact.delete()
                                const error = new Discord.MessageEmbed()
                                .setColor('#BB00EE')
                                .setTitle(":regional_indicator_x: Sorry we canceled your process becuase no language has been selected")
                                message.reply(error)
                            })

            }).catch(err => {
                console.log(err);
        });
    },
    
    requiredRoles: []
}