const axios = require('axios');

module.exports = {
    commands: 'server',
    expectedArgs: '<Server>',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord) => {
        axios.get('https://fn-api.com/api/status')
        .then((res) => {
            console.log(res.data);
            if (res.data.serverStatus[0].status === 'UP'){
                const Status = new Discord.MessageEmbed()
                .setColor('#BB00EE')
                .setTitle('Server Status')
                .setImage('https://i.imgur.com/k4Bhvfc.jpg')
                .setDescription('Fortnite is "' + res.data.serverStatus[0].status + '" right now')
                .addFields(
                    {name: 'Servers', value: res.data.serverStatus[0].launcherInfoDTO.appName},
                    {name: 'Description', value: res.data.serverStatus[0].message},
                    {name: 'Actions Allowed', value: res.data.serverStatus[0].allowedActions}
                )
                .setFooter('Generated By FNBR_MENA Bot')
                .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
                message.reply(Status);
                }

                if (res.data.serverStatus[0].status === 'DOWN'){
                    const Status = new Discord.MessageEmbed()
                    .setColor('#BB00EE')
                    .setTitle('Server Status')
                    .setImage('https://i.imgur.com/nYo2dxe.jpg')
                    .setDescription('Fortnite is "' + res.data.serverStatus[0].status + '" right now')
                    .addFields(
                        {name: 'Servers', value: res.data.serverStatus[0].launcherInfoDTO.appName},
                        {name: 'Description', value: res.data.serverStatus[0].message},
                        {name: 'Actions Allowed', value: res.data.serverStatus[0].allowedActions}
                    )
                    .setFooter('Generated By FNBR_MENA Bot')
                    .setAuthor('FNBR_MENA Bot', 'https://cdn.discordapp.com/attachments/756516105677177034/801215605461876776/THxzewFr_400x400.jpg', 'https://twitter.com/FNBR_MENA')
                    message.reply(Status);
                    }
        })
        .catch((err) => {
            console.log(err)
        })
    },
    
    requiredRoles: []
}