const axios = require('axios');
const Canvas = require('canvas')

module.exports = {
    commands: 'section',
    expectedArgs: '<Section>',
    minArgs: 0,
    maxArgs: 0,
    cooldown: -1,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, args, text, Discord, client, admin, alias, errorEmoji, checkEmoji) => {
        axios.get('https://fn-api.com/api/shop_categories')
        .then(async (res) => {
            const Sections = new Discord.MessageEmbed()
            Sections.setColor('#BB00EE')
            Sections.setTitle('Itemshop Sections')
            Sections.setDescription('All the itemshop sections from the API')
            for (let i = 0; i < res.data.shopCategories.length; i++) {
                Sections.addFields({
                    name: res.data.shopCategories[i].sectionName,
                    value: res.data.shopCategories[i].quantity + ' | Tab',
                    inline: true
                })
            }
            Sections.setFooter('Generated By FNBRMENA Bot')
            Sections.setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')
            message.reply(Sections);
        })
        .catch((err) => {
            console.log(err)
        })
    },
}