module.exports = {
    commands: 'social',
    expectedArgs: '<Social>',
    minArgs: 0,
    maxArgs: 0,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: (message, arguments, text, Discord) => {
        const exampleEmbed = new Discord.MessageEmbed()
        .setColor('#BB00EE')
        .setTitle('Social Media')
        .addFields(
            {name: 'Twitter', value: 'https://twitter.com/FNBR_MENA'},
            {name: 'TikTok', value: 'https://www.tiktok.com/@fnbr_mena'}
        )
        .setDescription('Thank You For Following Me (=')
        .setFooter('Generated By FNBR_MENA Bot')
        .setAuthor('FNBR_MENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBR_MENA')
        message.reply(exampleEmbed);
    },
    
    requiredRoles: []
}