module.exports = {
    commands: 'social',
    type: 'Fortnite',
    minArgs: 0,
    maxArgs: 0,
    cooldown: -1,
    permissionError: 'Sorry you do not have acccess to this command',
    callback: async (FNBRMENA, message, args, text, Discord, client, admin, userData, alias, emojisObject) => {
        
        const exampleEmbed = new Discord.EmbedBuilder()
        .setColor(FNBRMENA.Colors("embed"))
        .setTitle('Social Media')
        .addFields(
            {name: 'Twitter', value: 'https://twitter.com/FNBRMENA'},
            {name: 'TikTok', value: 'https://www.tiktok.com/@fnbrmena'}
        )
        .setDescription('Thank You For Following Me (=')
        .setFooter({text: 'Generated By FNBRMENA Bot'})
        .setAuthor({name: 'FNBRMENA Bot', iconURL: 'https://i.imgur.com/LfotEkZ.jpg', url: 'https://twitter.com/FNBRMENA'})
        message.reply({embeds: [exampleEmbed]});
    },
}