module.exports = {
    commands: 'help',
    type: 'Fortnite',
    minArgs: 0,
    maxArgs: 0,
    cooldown: -1,
    callback: async (FNBRMENA, message, args, text, Discord, client, admin, userData, alias, emojisObject) => {
        const help = new Discord.EmbedBuilder()
        .setColor(FNBRMENA.Colors("embed"))
        .setTitle('Help Section')
        .addFields(
            {name: '-Commands', value: 'Use that command to find all the FNBRMENA bot commands'}
        )
        .setDescription('Go to help if you have any issues there you will find all the helpful content')
        .setFooter({text: 'Generated By FNBRMENA Bot'})
        .setAuthor({name: 'FNBRMENA Bot', iconURL: 'https://i.ibb.co/xXVZYQZ/LfotEkZ.jpg', url: 'https://twitter.com/FNBRMENA'})
        message.reply({embeds: [help], components: [], files: []})
        .catch(err => {
            FNBRMENA.Logs(admin, client, Discord, message, alias, userData.lang, text, err, emojisObject, null)
        })
    },
}