const FortniteAPI = require("fortniteapi.io-api");
const Discord = require('discord.js')
const moment = require('moment')
const key = require('../Coinfigs/config.json')
const fortniteAPI = new FortniteAPI(key.apis.fortniteio);
const Canvas = require('canvas');
const config = require('../Coinfigs/config.json')
const isEqual = require('lodash.isequal')

module.exports = (client, admin) => {
    const message = client.channels.cache.find(channel => channel.id === config.events.Playlists)

    //result
    var resonse = []
    var modeName = []
    var number = 0

    const Playlists = async () => {

        //checking if the bot on or off
        admin.database().ref("ERA's").child("Events").child("playlists").once('value', async function (data) {
            var status = data.val().Active;
            var lang = data.val().Lang;
            var push = data.val().Push

            //if the event is set to be true [ON]
            if(status === "true"){
                
                //get the current game modes
                fortniteAPI.listCurrentGameModes(options = {lang: lang})
                .then(async res => {

                    //filter only enabled modes
                    const Active = await res.modes.filter(avaliable => {
                        return avaliable.enabled === true
                    })

                    //check for a change
                    if(number === 0){
                        resonse = await Active
                        for(let i = 0; i < Active.length; i++){
                            modeName[i] = Active[i].name
                        }
                        number++
                    }

                    //if the data was not the same
                    if(!isEqual(Active, resonse)){

                        //date
                        moment.locale(lang)
                        if(lang === "en"){
                            var date = date = moment().format("dddd, MMMM Do from YYYY")
                        }else if(lang === "ar"){
                            var date = date = moment().format("dddd, MMMM Do من YYYY")
                        }

                        //loop throw every active playlists
                        for(let i = 0; i < Active.length; i++){

                            //if the playlist isn't in the response array
                            if(!modeName.includes(Active[i].name)){

                                //create embed
                                const ActivePlaylist = new Discord.MessageEmbed()

                                //set the embed color
                                ActivePlaylist.setColor('#BB00EE')

                                if(lang === "en"){

                                    //add title and fields [EN]
                                    ActivePlaylist.setTitle("A new active playlist " + Active[i].name)
                                    ActivePlaylist.addFields(
                                        {name: "Max Team Size:", value: Active[i].maxTeamSize},
                                        {name: "Date:", value: date},
                                    )
                                }else if(lang === "ar"){

                                    //add title and fields [AR]
                                    ActivePlaylist.setTitle("تم تفعيل طور جديد " + Active[i].name)
                                    ActivePlaylist.addFields(
                                        {name: "عدد التيم:", value: Active[i].maxTeamSize},
                                        {name: "التاريخ:", value: date},
                                    )
                                }

                                //description
                                ActivePlaylist.setDescription(Active[i].description)

                                //add emage and credits stuff
                                ActivePlaylist.setImage(Active[i].image)
                                ActivePlaylist.setFooter('Generated By FNBRMENA Bot')
                                ActivePlaylist.setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')

                                //send the embed
                                await message.send(ActivePlaylist)
                            }
                        }

                        //restore data
                        resonse = await Active
                        for(let i = 0; i < Active.length; i++){
                            modeName[i] = Active[i].name
                        }
                    }
                }).catch(err => {
                    console.log("The issue is in Playlists Events ", err)
                })
            }
        })
    }
    setInterval(Playlists, 2.5 * 60000)
}