const axios = require('axios')
const Discord = require('discord.js')
const config = require('../Coinfigs/config.json')

module.exports = (client, admin) => {
    const message = client.channels.cache.find(channel => channel.id === config.events.Section)
    //result
    var data = []
    var number = 0

    const Section = async () => {
        axios.get('https://fn-api.com/api/shop_categories')
            .then(async res => {
                if (number === 0) {
                    data = res.data.shopCategories
                    number++
                }
                if (JSON.stringify(res.data.shopCategories) !== JSON.stringify(data)) {
                    const Sections = new Discord.MessageEmbed()
                    Sections.setColor('#BB00EE')
                    Sections.setTitle('Itemshop Sections')
                    Sections.setDescription('All the itemshop sections from the API')
                    for (let i = 0; i < res.data.shopCategories.length; i++) {
                        Sections.addFields({
                            name: res.data.shopCategories[i].sectionName,
                            value: res.data.shopCategories[i].quantity + ' | Tab',
                            inline: true
                        })
                    }
                    Sections.setFooter('Generated By FNBR_MENA Bot')
                    Sections.setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')
                    message.send(Sections);
                    data = res.data.shopCategories
                }
            })
    }
    setInterval(Section, 1 * 30000)
}