const axios = require('axios')
const Discord = require('discord.js')
const config = require('../Coinfigs/config.json')

module.exports = (client, admin) => {
    const message = client.channels.cache.find(channel => channel.id === config.events.Section)

    //result
    var response = []
    var number = 0
    var lang = "ar"

    const Section = async () => {

        //checking if the bot on or off
        admin.database().ref("ERA's").child("Events").child("section").once('value', async function (data) {
            var status = data.val().Active;
            if(status === "true"){

                //request data
                axios.get('https://fn-api.com/api/shop/sections?lang=' + lang)
                .then(async res => {

                    //store the data if the bot got restarted
                    if (number === 0) {
                        response = res.data.data.sections
                        number++
                    }

                    //checking for deff
                    if (JSON.stringify(res.data.data.sections) !== JSON.stringify(response)) {

                        //create embed
                        const Sections = new Discord.MessageEmbed()

                        //add the color
                        Sections.setColor('#BB00EE')

                        //add title
                        if(lang === "en"){
                            Sections.setTitle('Itemshop Sections')
                            Sections.setDescription('All the itemshop sections from the API')
                        }else if(lang === "ar"){
                            Sections.setTitle('عناصر الشوب')
                            Sections.setDescription('جميع عناصر الشوب من الـ API')
                        }
                        
                        for (let i = 0; i < res.data.data.sections.length; i++) {
                            
                            //add fields
                            if(lang === "en"){
                                Sections.addFields({
                                    name: res.data.data.sections[i].name,
                                    value: res.data.data.sections[i].quantity + ' | Tab',
                                })
                            }else if(lang === "ar"){
                                Sections.addFields({
                                    name: res.data.data.sections[i].name,
                                    value: res.data.data.sections[i].quantity + ' | صفحه',
                                })
                            }

                        }
                        Sections.setFooter('Generated By FNBRMENA Bot')
                        Sections.setAuthor('FNBRMENA Bot', 'https://i.imgur.com/LfotEkZ.jpg', 'https://twitter.com/FNBRMENA')
                        message.send(Sections);
                        response = res.data.data.sections
                    }
                }).catch(err => {
                    console.log("The issue is in ShopSection Events ", err)
                })
            }
        })
    }
    setInterval(Section, 1 * 30000)
}