name: Auto Deploy FNBRMENA Bot On Master Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy App files to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" scp -o StrictHostKeyChecking=no -r App/ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/App/

      - name: Deploy to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no -nT ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/App
            docker build --no-cache -t fnbrmena_image:latest .
            docker stop FNBRMENA_CONTAINER || true
            docker rm FNBRMENA_CONTAINER || true
            docker run -d --name FNBRMENA_CONTAINER fnbrmena_image:latest
          EOF
