name: Auto Deploy FNBRMENA Bot On Master Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --platform linux/arm64 -t fnbrmena_image:latest .

      - name: Save Docker image to file
        run: |
          docker save fnbrmena_image:latest -o fnbrmena_image.tar

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Transfer Docker image to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" scp -o StrictHostKeyChecking=no fnbrmena_image.tar ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/tmp

      - name: Deploy to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            docker rm -f FNBRMENA_CONTAINER || true
            docker load -i /tmp/fnbrmena_image.tar
            docker run -d --name FNBRMENA_CONTAINER fnbrmena_image:latest
          EOF
