name: Auto Deploy FNBRMENA Bot

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create TAR file
        run: |
          tar -cvf FNBRMENA.tar App Dockerfile

      - name: Transfer TAR file to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" scp -o StrictHostKeyChecking=no FNBRMENA.tar ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/tmp/fnbrmena_repo/

      - name: Deploy and Build Docker image on VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /tmp/fnbrmena_repo
            tar -xf FNBRMENA.tar
            rm -rf FNBRMENA.tar
            docker rm -f FNBRMENA_CONTAINER || true
            docker rmi fnbrmena_image || true
            docker build --no-cache -t fnbrmena_image:latest .
            
            # Determine the correct Discord token based on the branch
            if [ "${GITHUB_REF##*/}" == "master" ]; then
              discord_token="${{ secrets.PRD_DISCORD_TOKEN }}"
            else
              discord_token="${{ secrets.DEV_DISCORD_TOKEN }}"
            fi
            
            docker run -d --name FNBRMENA_CONTAINER \
              --restart always \
              -e type="${{ secrets.FIREBASE_TYPE }}" \
              -e project_id="${{ secrets.FIREBASE_PROJECT_ID }}" \
              -e private_key_id="${{ secrets.FIREBASE_PRIVATE_KEY_ID }}" \
              -e private_key="${{ secrets.FIREBASE_PRIVATE_KEY }}" \
              -e client_email="${{ secrets.FIREBASE_CLIENT_EMAIL }}" \
              -e client_id="${{ secrets.FIREBASE_CLIENT_ID }}" \
              -e auth_uri="${{ secrets.FIREBASE_AUTH_URI }}" \
              -e token_uri="${{ secrets.FIREBASE_TOKEN_URI }}" \
              -e auth_provider_x509_cert_url="${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}" \
              -e client_x509_cert_url="${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}" \
              -e universe_domain="${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}" \
              -e discord_token="$discord_token" \
              fnbrmena_image:latest
            rm -rf *
          EOF
